(chore): fix reconcile plugin on plugin definition change (#1406) (#1410)
(chore): update fixtures

(chore): split plugin e2e into sub scenarios

(chore): use scenarios in plugin e2e

(chore): remove unused import

(chore): add license headers

(chore): fix lint errors

(chore): fix lint errors

(chore): fix typo

(chore): simplify watches

(chore): fix tests

(chore): tidy up!

(chore): fix flux scenario e2e test

(chore): fix flux scenario e2e test

(chore): debug helm release in actions

(chore): wait for flux helm controller deployment to be available

(chore): generate flux pod logs

(chore): use label constants

(chore): print pod logs on test failure

(chore): print pod logs on test failure

(chore): adds failure check on print pod logs

(chore): merge helm and flux controllers

(chore): unique test resource names

(chore): fix multiple scheme writes

(chore): fix lint errors

(chore): remove multiple scheme registration

(chore): remove err context

(chore): remove label selector in enqueue request

(chore): keep concurrent reconcile to 10

(chore): remove wait for flux deployment

(chore): adds github token env in e2e workflow

(chore): add echo stmt

(chore): fix line termination

(chore): add github token env to unit tests


(cherry picked from commit a4fc9c1b7a2224ee3511126284d9992dc845a4a1)

Signed-off-by: abhijith-darshan <abhijith.darshan@hotmail.com>
Co-authored-by: Abhijith Ravindra <137736216+abhijith-darshan@users.noreply.github.com>

diff --git a/.github/workflows/ci-e2e-test.yaml b/.github/workflows/ci-e2e-test.yaml
--- a/.github/workflows/ci-e2e-test.yaml
+++ b/.github/workflows/ci-e2e-test.yaml
@@ -34,6 +34,8 @@ jobs:
     if: needs.init.outputs.tests != '[]'
     needs: [ init ]
     runs-on: [ default ]
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     strategy:
       fail-fast: false
       matrix:
@@ -43,12 +45,24 @@ jobs:
       # run the e2e tests using composite common/workflows/e2e action
       - name: "E2E"
         id: e2e
+        continue-on-error: true
         uses: cloudoperators/common/workflows/e2e@main
         with:
           k8s-version: ${{ matrix.k8s-version }}
           scenario: ${{ matrix.e2es }}
           admin-config: ${{ github.workspace }}/dev-env/greenhouse-admin-cluster.yaml
           remote-config: ${{ github.workspace }}/dev-env/greenhouse-remote-cluster.yaml
+
+      - name: "Display Logs"
+        if: ${{ steps.e2e.outcome == 'failure' }}
+        run: |
+          echo "Displaying greenhouse controller logs for failed scenario: ${{ matrix.e2es }}"
+          cat ${{ github.workspace }}/bin/${{ matrix.e2es }}-${{ matrix.k8s-version }}.txt
+          echo "----------------------------------------"
+          echo "Displaying flux logs for failed scenario: ${{ matrix.e2es }}"
+          cat ${{ github.workspace }}/bin/flux-${{ matrix.e2es }}-${{ matrix.k8s-version }}.txt
+          exit 1
+        
 
   # check if the e2e tests passed for all scenarios
   checksOK:
